From node:22.15.1-alpine

LABEL version="1.0"
LABEL description="React Frontend for the Real Estate API"

WORKDIR /app

COPY ./package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

CMD ["npm", "run", "start", "--openssl-legacy-provider"]