# Generated by Django 3.2.7 on 2025-01-15 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+5561999999999', max_length=30, region=None, verbose_name='Phone Number')),
                ('about_me', models.TextField(default='Diga algo sobre você', verbose_name='About Me')),
                ('license', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do CRECI')),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='profile_photos', verbose_name='Profile Photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(default='BR', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Brasília', max_length=18, verbose_name='Cidade')),
                ('is_Buyer', models.BooleanField(default=False, help_text='Você está procurando comprar um imóvel?', verbose_name='Comprador')),
                ('is_Seller', models.BooleanField(default=False, help_text='Você está procurando vender um imóvel?', verbose_name='Vendedor')),
                ('is_Agent', models.BooleanField(default=False, help_text='Você é um corretor de imóveis?', verbose_name='Corretor')),
                ('top_agent', models.BooleanField(default=False, verbose_name='Corretor Ranqueado')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de Avaliações')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
