# Generated by Django 3.2.7 on 2025-01-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_Agent',
            new_name='is_agent',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_Buyer',
            new_name='is_buyer',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_Seller',
            new_name='is_seller',
        ),
    ]
