# Generated by Django 3.2.7 on 2025-02-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='Default description...update me please ...', verbose_name='Descriprion'),
        ),
    ]
