# Generated by Django 3.2.7 on 2025-01-15 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_profile_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, 'RUIM'), (2, 'REGULAR'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')], default=0, help_text='1=Ruim, 2=Regular, 3=Bom, 4=Muito Bom, 5=Excelente', verbose_name='Avaliação')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_reveiw', to='profiles.profile', verbose_name='Corretor')),
                ('rater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Votante')),
            ],
            options={
                'unique_together': {('rater', 'agent')},
            },
        ),
    ]
